# 生成共用的certificate或秘钥
- name: Create kubernetes certificate request configuration
  template: 
    src: kube-openssl.cnf.j2
    dest: /etc/kubernetes/pki/kube-openssl.cnf
    owner: root
    mode: 0644

- name: Create kubernetes-ca root certificate private key
  shell: openssl genrsa -out /etc/kubernetes/pki/ca.key 2048
  when: ca_key_stat.stat.isreg is not defined

- name: Create kubernetes-ca root certificate
  shell: >
    openssl req -x509 -new -nodes
    -extensions v3_ca -subj "/CN=kubernetes"
    -config /etc/kubernetes/pki/kube-openssl.cnf
    -key /etc/kubernetes/pki/ca.key
    -out /etc/kubernetes/pki/ca.crt
    -days {{ certs_expired }}
  when: ca_crt_stat.stat.isreg is not defined

- name: Create front-proxy-ca certificate private key
  shell: openssl genrsa -out /etc/kubernetes/pki/front-proxy-ca.key 2048
  when: front_proxy_ca_key_stat.stat.isreg is not defined

- name: Create front-proxy-ca root certificate
  shell: >
    openssl req -x509 -new -nodes
    -extensions v3_ca -subj "/CN=kubernetes"
    -config /etc/kubernetes/pki/kube-openssl.cnf
    -key /etc/kubernetes/pki/front-proxy-ca.key
    -out /etc/kubernetes/pki/front-proxy-ca.crt
    -days {{ certs_expired }}
  when: front_proxy_ca_crt_stat.stat.isreg is not defined

- name: Create apiserver certificate private key
  shell: openssl genrsa -out /etc/kubernetes/pki/apiserver.key 2048
  when: apiserver_key_stat.stat.isreg is not defined

- name: Create apiserver certificate request
  shell: >
    openssl req -new 
    -subj "/CN=kube-apiserver" 
    -key /etc/kubernetes/pki/apiserver.key 
    -out /etc/kubernetes/pki/apiserver.csr
  
- name: Create apiserver certificate
  shell: >
    openssl x509 -req -CAcreateserial 
    -extensions v3_req_server 
    -extfile /etc/kubernetes/pki/kube-openssl.cnf 
    -CA /etc/kubernetes/pki/ca.crt 
    -CAkey /etc/kubernetes/pki/ca.key 
    -in /etc/kubernetes/pki/apiserver.csr
    -out /etc/kubernetes/pki/apiserver.crt
    -days {{ certs_expired }}

- name: Create apiserver-kubelet-client certificate private key
  shell: openssl genrsa -out /etc/kubernetes/pki/apiserver-kubelet-client.key 2048
  when: apiserver_kubelet_client_key_stat.stat.isreg is not defined

- name: Create apiserver-kubelet-client certificate request
  shell: >
    openssl req -new 
    -subj "/CN=kube-apiserver-kubelet-client/O=system:masters"
    -key /etc/kubernetes/pki/apiserver-kubelet-client.key 
    -out /etc/kubernetes/pki/apiserver-kubelet-client.csr

- name: Create apiserver-kubelet-client certificate
  shell: >
    openssl x509 -req -CAcreateserial 
    -extensions v3_req_client 
    -extfile /etc/kubernetes/pki/kube-openssl.cnf 
    -CA /etc/kubernetes/pki/ca.crt 
    -CAkey /etc/kubernetes/pki/ca.key 
    -in /etc/kubernetes/pki/apiserver-kubelet-client.csr
    -out /etc/kubernetes/pki/apiserver-kubelet-client.crt
    -days {{ certs_expired }}

- name: Create front-proxy-client certificate private key
  shell: openssl genrsa -out /etc/kubernetes/pki/front-proxy-client.key 2048
  when: front_proxy_client_key_stat.stat.isreg is not defined

- name: Create front-proxy-client certificate request
  shell: >
    openssl req -new 
    -subj "/CN=front-proxy-client"
    -key /etc/kubernetes/pki/front-proxy-client.key 
    -out /etc/kubernetes/pki/front-proxy-client.csr

- name: Create front-proxy-client certificate
  shell: >
    openssl x509 -req -CAcreateserial 
    -extensions v3_req_client 
    -extfile /etc/kubernetes/pki/kube-openssl.cnf 
    -CA /etc/kubernetes/pki/front-proxy-ca.crt
    -CAkey /etc/kubernetes/pki/front-proxy-ca.key
    -in /etc/kubernetes/pki/front-proxy-client.csr
    -out /etc/kubernetes/pki/front-proxy-client.crt
    -days {{ certs_expired }}

- name: Create kube-scheduler certificate private key
  shell: openssl genrsa -out /etc/kubernetes/pki/kube-scheduler.key 2048
  when: kube_scheduler_key_stat.stat.isreg is not defined

- name: Create kube-scheduler certificate request
  shell: >
    openssl req -new 
    -subj "/CN=system:kube-scheduler" 
    -key /etc/kubernetes/pki/kube-scheduler.key
    -out /etc/kubernetes/pki/kube-scheduler.csr

- name: Create kube-scheduler certificate
  shell: >
    openssl x509 -req -CAcreateserial 
    -extensions v3_req_client 
    -extfile /etc/kubernetes/pki/kube-openssl.cnf 
    -CA /etc/kubernetes/pki/ca.crt 
    -CAkey /etc/kubernetes/pki/ca.key 
    -in /etc/kubernetes/pki/kube-scheduler.csr
    -out /etc/kubernetes/pki/kube-scheduler.crt
    -days {{ certs_expired }}

- name: Create sa certificate private key
  shell: openssl genrsa -out /etc/kubernetes/pki/sa.key 2048
  when: sa_key_stat.stat.isreg is not defined

- name: Generate the public key from the sa private key
  shell: openssl rsa -in /etc/kubernetes/pki/sa.key -pubout -out /etc/kubernetes/pki/sa.pub
  when: sa_pud_stat.stat.isreg is not defined

- name: link sa certificate private key to kube-controller-manager certificate private key
  file: 
    src: /etc/kubernetes/pki/sa.key
    dest: /etc/kubernetes/pki/kube-controller-manager.key
    state: link
  run_once: true
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: Create kube-controller-manager certificate request
  shell: >
    openssl req -new 
    -subj "/CN=system:kube-controller-manager" 
    -key /etc/kubernetes/pki/sa.key 
    -out /etc/kubernetes/pki/kube-controller-manager.csr

- name: Create kube-controller-manager certificate
  shell: >
    openssl x509 -req -CAcreateserial 
    -extensions v3_req_client 
    -extfile /etc/kubernetes/pki/kube-openssl.cnf 
    -CA /etc/kubernetes/pki/ca.crt 
    -CAkey /etc/kubernetes/pki/ca.key 
    -in /etc/kubernetes/pki/kube-controller-manager.csr
    -out /etc/kubernetes/pki/kube-controller-manager.crt
    -days {{ certs_expired }}

- name: Create kubernetes cluster admin certificate private key
  shell: openssl genrsa -out /etc/kubernetes/pki/admin.key 2048
  when: admin_key_stat.stat.isreg is not defined

- name: Create kubernetes cluster admin certificate request
  shell: >
    openssl req -new 
    -subj "/CN=kubernetes-admin/O=system:masters"
    -key /etc/kubernetes/pki/admin.key
    -out /etc/kubernetes/pki/admin.csr

- name: Create kubernetes cluster admin certificate
  shell: >
    openssl x509 -req -CAcreateserial 
    -extensions v3_req_client
    -extfile /etc/kubernetes/pki/kube-openssl.cnf
    -CA /etc/kubernetes/pki/ca.crt 
    -CAkey /etc/kubernetes/pki/ca.key
    -in /etc/kubernetes/pki/admin.csr
    -out /etc/kubernetes/pki/admin.crt
    -days {{ certs_expired }}

- name: Create kubelet certificate private key
  shell: openssl genrsa -out /var/lib/kubelet/pki/kubelet.key 2048
  when: kubelet_key_stat.stat.isreg is not defined

- name: Create kubelet certificate request
  shell: >
    openssl req -new 
    -subj "/CN=kubelet" 
    -key /var/lib/kubelet/pki/kubelet.key
    -out /var/lib/kubelet/pki/kubelet.csr
  
- name: Create kubelet server certificate
  shell: >
    openssl x509 -req -CAcreateserial 
    -extensions v3_req_kubelet 
    -extfile /etc/kubernetes/pki/kube-openssl.cnf 
    -CA /etc/kubernetes/pki/ca.crt 
    -CAkey /etc/kubernetes/pki/ca.key 
    -in /var/lib/kubelet/pki/kubelet.csr
    -out /var/lib/kubelet/pki/kubelet.crt
    -days {{ certs_expired }}

- name: Retrieves the control node request file that needs to be cleaned
  find:
    paths: /etc/kubernetes/pki/
    patterns: '*.csr'
  register: files_to_purge_for_csr

- name: Clean up control node certificate request file
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ files_to_purge_for_csr.files }}"

- name: Clean up kubelet certificate request file
  file:
    path: /var/lib/kubelet/pki/kubelet.csr
    state: absent