- block:
  - name: Download govc file
    get_url:
      validate_certs: no
      url: "{{ govc_download_url }}"
      dest: "{{ base_dir }}/"
      timeout: "{{ download_timeout_online }}"

  - name: Unarchive govc file
    shell: "gunzip {{ base_dir }}/govc_linux_{{ architectures }}.gz"

  - name: Copy govc file
    copy:
      src: "{{ base_dir}}/govc_linux_{{ architectures }}"
      dest: "{{ bin_dir }}/govc"
      remote_src: yes
      mode: "0755"

  - name: Remove govc file
    file:
      name: "{{ base_dir }}/govc_linux_{{ architectures }}"
      state: absent

  - name: Create cloud-config directory
    file:
      name: "{{ cloud_config_dir }}"
      state: directory

  - name: prepare setup.sh
    template:
      src: vsphere/setup.sh.j2
      dest: "{{ cloud_config_dir }}/setup.sh"

  - name: install jq
    package:
      name:
      - jq

  - name: Set disk.enableuuid to true for all vms
    shell: "bash setup.sh"
    args:
      chdir: "{{ cloud_config_dir }}"
  delegate_to: "{{ groups['kube-master'][0] }}"

- name: Modify kubelet cloud provider params on worker
  lineinfile:
    dest: /etc/sysconfig/kubelet
    regexp: '^KUBELET_EXTRA_ARGS'
    line: 'KUBELET_EXTRA_ARGS=--cgroup-driver=cgroupfs --cloud-provider=vsphere'
  when: ansible_distribution in ["CentOS","RedHat","EulerOS"]

- name: Modify kubelet cloud provider params on worker
  lineinfile:
    dest: /etc/default/kubelet
    regexp: '^KUBELET_EXTRA_ARGS'
    line: 'KUBELET_EXTRA_ARGS=--cgroup-driver=cgroupfs --cloud-provider=vsphere'
  when: ansible_distribution in [ 'Ubuntu','Debian' ]

- name: Systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: Restart docker
  service:
    name: docker
    state: restarted
  delegate_to: "{{ item }}"
  with_items:
  - "{{ groups['kube-master'] }}"
  - "{{ groups['kube-worker'] }}"
  - "{{ groups['new-worker'] }}"

- name: Restart kubelet
  service:
    name: kubelet
    state: restarted
  delegate_to: "{{ item }}"
  with_items:
    - "{{ groups['kube-master'] }}"
    - "{{ groups['kube-worker'] }}"
    - "{{ groups['new-worker'] }}"