# 提权操作
ansible_become: true
# 当前节点ip
CURRENT_HOST_IP: "{% if hostvars[inventory_hostname]['ansible_host'] is defined %}{{ hostvars[inventory_hostname]['ansible_host'] }}{% else %}{{ inventory_hostname }}{% endif %}"
# etcd 集群
INITIAL_CLUSTER: "{% for host in (groups['etcd']|unique) %}{% if hostvars[host]['ansible_host'] is defined %}etcd-{{ host }}=https://{{ hostvars[host]['ansible_host'] }}:2380{% else %}etcd-{{ host }}=https://{{ host }}:2380{% endif %}{% if not loop.last %},{% endif %}{% endfor %}"